# -*- coding: utf-8 -*-
"""lab09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fNghWIFVndTIO_dJYT-bqqR1459o-id
"""

alfabeto = {
  'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 1,
  'k': 2, 'l': 3, 'm': 4, 'n': 5, 'o': 6, 'p': 7, 'q': 8, 'r': 9, 's': 1,
  't': 2, 'u': 3, 'v': 4, 'w': 5, 'x': 6, 'y': 7, 'z': 8
}


N = int(input().strip())
modificadores = input().split()

for i in range(len(modificadores)):
    modificadores[i] = int(modificadores[i])
for i,l in enumerate(alfabeto):
    if(modificadores[i]==0):
        alfabeto[l]=0

resultados=[]
for i in range(N):
    op = input().split()


    palavra_pra_numero = []
    operadores = []

    for valor in op:
        valor = valor.lower()

        if valor == '+' or valor == '-':
            operadores.append(valor)
            continue

        numero_da_palavra = 0
        elevado = len(valor)

        for letra in valor:
            if letra in alfabeto:
                base = alfabeto[letra]
                numero_da_palavra = numero_da_palavra + (base * (10 ** (elevado - 1)))
                elevado = elevado - 1

        palavra_pra_numero.append(numero_da_palavra)


    if len(palavra_pra_numero) > 0:
        resultado_linha = palavra_pra_numero[0]
        for j in range(len(operadores)):
            if operadores[j] == '+':
                resultado_linha = resultado_linha + palavra_pra_numero[j + 1]

            else:
                resultado_linha = resultado_linha - palavra_pra_numero[j + 1]

        resultados.append(resultado_linha)


for i in resultados:
    print(i)

