# -*- coding: utf-8 -*-
"""lab11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTrGXiI1zxJO49TK-wBjVKVOJ-bRKW25
"""

# Leitura dos valores de A e J
entrada = input().split()
a = int(entrada[0])  # número de andares (linhas)
j = int(entrada[1])  # número de janelas por face (colunas)

# Ordem circular das faces para movimentação e também impressão de referência
# Ajuste principal: usar N, O, S, L como ordem circular
lados = ["N", "O", "S", "L"]

# Criação do prédio como dicionário de faces (N, O, S, L)
faces = {}

def criar_matriz(a, j):
    matriz = []
    for i in range(a):
        linha = []
        for k in range(j):
            linha.append("#")
        matriz.append(linha)
    return matriz

for face in lados:
    faces[face] = criar_matriz(a, j)

# Estado inicial
andar_atual = 0
pos_atual = 0
indice_face = 0  # começa em "N" (lados[0])

# Limpa a janela inicial (regra típica: limpa ao passar/estar)
faces[lados[indice_face]][andar_atual][pos_atual] = "."

# Funções de movimento
def Direita(predio, qtd, J, lados_faces, face_indice_atual, andar_atual, pos_atual):
    passos = 0
    while passos < qtd:
        nome_face = lados_faces[face_indice_atual]
        # limpa onde está antes de se mover (passar)
        predio[nome_face][andar_atual][pos_atual] = "."
        if (pos_atual + 1) >= J:
            # troca de face ao cruzar a borda direita
            face_indice_atual = (face_indice_atual + 1) % len(lados_faces)
            pos_atual = 0
        else:
            pos_atual += 1
        passos += 1
    # limpa a posição final (estar)
    predio[lados_faces[face_indice_atual]][andar_atual][pos_atual] = "."
    return face_indice_atual, andar_atual, pos_atual

def Esquerda(predio, qtd, J, lados_faces, face_indice_atual, andar_atual, pos_atual):
    passos = 0
    while passos < qtd:
        nome_face = lados_faces[face_indice_atual]
        # limpa onde está antes de se mover (passar)
        predio[nome_face][andar_atual][pos_atual] = "."
        if (pos_atual - 1) < 0:
            # troca de face ao cruzar a borda esquerda
            face_indice_atual = (face_indice_atual - 1) % len(lados_faces)
            pos_atual = J - 1
        else:
            pos_atual -= 1
        passos += 1
    # limpa a posição final (estar)
    predio[lados_faces[face_indice_atual]][andar_atual][pos_atual] = "."
    return face_indice_atual, andar_atual, pos_atual

def Cima(predio, qtd, A, lados_faces, face_indice_atual, andar_atual, pos_atual):
    passos = 0
    while passos < qtd:
        nome_face = lados_faces[face_indice_atual]
        # limpa onde está antes de se mover (passar)
        predio[nome_face][andar_atual][pos_atual] = "."
        # sobe até o topo (andar 0); se já está no topo, não sobe mais, mas consome o passo
        if (andar_atual - 1) >= 0:
            andar_atual -= 1
        passos += 1
    # limpa a posição final (estar)
    predio[lados_faces[face_indice_atual]][andar_atual][pos_atual] = "."
    return face_indice_atual, andar_atual, pos_atual

def Baixo(predio, qtd, A, lados_faces, face_indice_atual, andar_atual, pos_atual):
    passos = 0
    while passos < qtd:
        nome_face = lados_faces[face_indice_atual]
        # limpa onde está antes de se mover (passar)
        predio[nome_face][andar_atual][pos_atual] = "."
        # desce até o último andar (A-1); se já está no último, não desce mais, mas consome o passo
        if (andar_atual + 1) < A:
            andar_atual += 1
        passos += 1
    # limpa a posição final (estar)
    predio[lados_faces[face_indice_atual]][andar_atual][pos_atual] = "."
    return face_indice_atual, andar_atual, pos_atual

# Leitura e processamento dos comandos
while(True):
    direcao = input().split()
    if direcao[0] == 'F':
        break
    qtd = int(direcao[1])
    if direcao[0] == 'D':
        indice_face, andar_atual, pos_atual = Direita(faces, qtd, j, lados, indice_face, andar_atual, pos_atual)
    elif direcao[0] == 'E':
        indice_face, andar_atual, pos_atual = Esquerda(faces, qtd, j, lados, indice_face, andar_atual, pos_atual)
    elif direcao[0] == 'C':
        indice_face, andar_atual, pos_atual = Cima(faces, qtd, a, lados, indice_face, andar_atual, pos_atual)
    elif direcao[0] == 'B':
        indice_face, andar_atual, pos_atual = Baixo(faces, qtd, a, lados, indice_face, andar_atual, pos_atual)

# Impressão do resultado final
def imprimir_predio(predio, ordem, A, J, lados_faces, face_idx_atual, andar_atual, pos_atual):
    for nome_face in ordem:
        print(f"Face {nome_face}")
        for andar in range(A):
            linha_str = ""
            for c in range(J):
                if (nome_face == lados_faces[face_idx_atual] and andar == andar_atual and c == pos_atual):
                    linha_str += "R"
                else:
                    linha_str += predio[nome_face][andar][c]
            print(linha_str)
        print("-" * J)


ordem_impressao = ["N", "O", "S", "L"]
imprimir_predio(faces, ordem_impressao, a, j, lados, indice_face, andar_atual, pos_atual)