# -*- coding: utf-8 -*-
"""lab15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVTZXXbJg0wipLwk8WJCGk2lT7cLlCGI
"""

entrada = input().split()
a = int(entrada[0])
j = int(entrada[1])
c = int(entrada[2])

lados = ["N", "O", "S", "L"]

janelas_sujas = []

while True:
    linha = input().split()
    face = linha[0]

    if face == 'F':
        break

    andar = int(linha[1])
    pos = int(linha[2])
    janelas_sujas.append((face, andar, pos - 1))

predio = janelas_sujas

def checar_limpeza(predio, f, a, j, n, c):
    lados = ["N", "O", "S", "L"]

    if n < 0:
        return False
    if not predio:
        return True

    for janela in predio:
        face_destino = janela[0]
        andar_destino = janela[1]
        janela_destino = janela[2]

        # ========== CALCULAR CUSTO VERTICAL ==========
        custo_v = 0
        comando_v = ''

        if andar_destino != a:
            comando_v = 'C' if andar_destino > a else 'B'
            custo_v = 0 if c in ['C', 'B'] else 1

        # ========== CALCULAR CUSTO HORIZONTAL ==========
        custo_h = 0
        comando_h = ''

        if face_destino != f or janela_destino != j:
            pos_face = lados.index(f)
            pos_face_destino = lados.index(face_destino)

            # Determinar direção
            if pos_face > pos_face_destino:
                comando_h = 'E'
            elif pos_face < pos_face_destino:
                comando_h = 'D'
            else:  # Mesma face
                comando_h = 'D' if janela_destino > j else 'E'

            custo_h = 0 if c in ['E', 'D'] else 1

        # ========== SOMAR UMA ÚNICA VEZ ==========
        custo_final = custo_v + custo_h

        # ========== DEFINIR COMANDO FINAL ==========
        if custo_h > 0:
            comando_final = comando_h
        elif custo_v > 0:
            comando_final = comando_v
        else:
            comando_final = c

        # ========== RECURSÃO ==========
        if n >= custo_final:
            copia_predio = predio.copy()
            copia_predio.remove(janela)

            if checar_limpeza(copia_predio, face_destino, andar_destino, janela_destino, n - custo_final, comando_final):
                return True

    return False

if checar_limpeza(janelas_sujas, 'N', 0, 0, c, 'X'):
    print("Comandos encontrados")
else:
    print("Comandos não encontrados")

