# -*- coding: utf-8 -*-
"""lab10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZYNqbIW-s_ZQ0Nx2UafePgw-WQnohJo
"""

cartela = [list(map(int, input().split())) for _ in range(5)]


marcada = [[0]*5 for _ in range(5)]

marcada[2][2] = 1


bingo = False  # <— mantém

# Passa a ler um número por vez
while True:
    rodada = int(input())
    for i in range(5):
        for j in range(5):
            if cartela[i][j] == rodada:
                marcada[i][j] = 1
    vencedores=[]

    vencedores=[]
    for r in range(5):
        cont = 0
        for c in range(5):
            if marcada[r][c] == 1:
                cont += 1
        if cont == 5:
            for o in range(5):
                vencedores.append(cartela[r][o])
            print(f"Os números da sorte foram: {vencedores[0]}, {vencedores[1]}, {vencedores[2]}, {vencedores[3]}, {vencedores[4]}")
            bingo = True
            break
    if bingo:
        break
    for c in range(5):
        cont = 0
        for r in range(5):
            if marcada[r][c] == 1:
                cont += 1
        if cont == 5:
            for o in range(5):
                vencedores.append(cartela[o][c])
            print(f"Os números da sorte foram: {vencedores[0]}, {vencedores[1]}, {vencedores[2]}, {vencedores[3]}, {vencedores[4]}")
            bingo = True
            break
    if bingo:
        break

    vencedores=[]
    cont = 0
    for k in range(5):
        if marcada[k][k] == 1:
            cont += 1
    if cont == 5:
        for o in range(5):
            vencedores.append(cartela[o][o])
        print(f"Os números da sorte foram: {vencedores[0]}, {vencedores[1]}, {vencedores[2]}, {vencedores[3]}, {vencedores[4]}")
        bingo=True
        break
    if bingo:
        break

    vencedores=[]
    cont = 0
    for k in range(5):
        if marcada[k][4-k] == 1:
            cont += 1
    if cont == 5:
        for o in range(5):
            vencedores.append(cartela[o][4-o])
        print(f"Os números da sorte foram: {vencedores[0]}, {vencedores[1]}, {vencedores[2]}, {vencedores[3]}, {vencedores[4]}")
        break
    if bingo:
        break