# -*- coding: utf-8 -*-
"""lab14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOFUv0glAYQze_FMmXkmz9J878PnLMQ5
"""

# Definição dos reagentes (original, mutação, custo)
reagentes = [
    ("A", "AT", 2),
    ("G", "GC", 2),
    ("TT", "A", 5),
    ("CG", "G", 1),
    ("AT", "TA", 1),
    ("C", "G", 3),
    ("T", "A", 3),
    ("AGA", "C", 8),
    ("CC", "G", 4),
    ("TATA", "GC", 10)
]

# Dicionário para memorização (chave: sequencia + custo usado)
memo = {}

def sintetizadorDNA(sequencia_atual, sequencia_final, custo_atual, MAX_CUSTO):
    # Caso base: já chegamos na sequência final
    if sequencia_atual == sequencia_final:
        return True

    # Se excedeu o orçamento, não é possível
    if custo_atual > MAX_CUSTO:
        return False

    # Verifica se já calculamos este estado (sequencia + custo usado)
    estado = (sequencia_atual, custo_atual)
    if estado in memo:
        return memo[estado]

    # Tenta aplicar cada reagente em cada posição
    for original, mutacao, custo in reagentes:
        # Procura todas as ocorrências do padrão original
        for i in range(len(sequencia_atual) - len(original) + 1):
            # Verifica se o padrão está nesta posição
            if sequencia_atual[i:i+len(original)] == original:
                # Aplica a mutação
                nova_sequencia = sequencia_atual[:i] + mutacao + sequencia_atual[i+len(original):]
                novo_custo = custo_atual + custo

                # Recursão: tenta continuar a partir desta nova sequência
                if sintetizadorDNA(nova_sequencia, sequencia_final, novo_custo, MAX_CUSTO):
                    memo[estado] = True
                    return True

    # Não conseguiu transformar
    memo[estado] = False
    return False


# Leitura de dados
MAX_CUSTO = int(input())
sequencia_inicial = input()
sequencia_final = input()

# Processamento da sequência
if sintetizadorDNA(sequencia_inicial, sequencia_final, 0, MAX_CUSTO):
    print("É possível sintetizar essa sequência.")
else:
    print("Não é possível sintetizar essa sequência.")